import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Provider } from 'react-redux';
import store from '@/redux/store/store';
import ReduxProvider from '@/app/ReduxProvider';
import TopHome from '@/component/app/home/top-off/home-component';
import HomeNavbar from '@/component/app/home/navbar/home-navbar';
import Footer from '@/component/app/home/section9/section9';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="ltr" lang="eng" className={'overflow-x-hidden bg-stone-200 '}>
      <body>
        <ReduxProvider>
          
          {children}
         
        </ReduxProvider>
      </body>
    </html>
  );
}
